### ISSUE TITLE
Deploy ReactJS frontend and push to github

### ISSUE THREAD

**Issue by tatedean** [bytesandbrews-smtx/roulette-bites#6]
Do it

**Comment by tatedean** [comment]
@symbiontik completed this issue. We have a React base project in the github that anyone can pull and run locally. See image:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/41554005/207358156-92d76ad3-e4cf-4574-bf6f-b4731bb61512.png">

**Comment by symbiontik** [comment]
Completed this issue with the following PR:
https://github.com/bytesandbrews-smtx/roulette-bites/pull/11
