### ISSUE TITLE
Create frontend button to randomly pick restaurant from sample data

### ISSUE THREAD

**Issue by tatedean** [bytesandbrews-smtx/roulette-bites#9]
Finishing this issue will complete this Milestone. We will have a MVP once this is done!

This button will randomly pick a restaurant from the 10x sample data and display it to the user.

**Comment by tatedean** [comment]
Put button in project which randomly selects a restaurant from a flat list of 4 then prints to console.

<img width="680" alt="image" src="https://user-images.githubusercontent.com/41554005/207370578-686f9645-810e-4936-97b0-13090351c272.png">

**Comment by benhprentice** [comment]
<img width="1440" alt="Screenshot 2023-01-10 at 8 28 02 AM" src="https://user-images.githubusercontent.com/90800451/211578025-3b4567c0-942e-4d60-b6f0-c5d479008cdc.png">
